# This workflow will install Python dependencies, run tests, and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.6"
    
    - name: Check for requirements.txt
      run: |
        if [ ! -f requirements.txt ]; then
          echo "Error: requirements.txt not found!"
          exit 1
        fi
    
    - name: Install dependencies using Makefile
      run: |
        make install
    
    - name: Run the Flask server
      run: |
        make run &
        sleep 10  # Give the server time to start

    - name: Test with pytest
      run: |
        . venv/bin/activate && pytest
      env:
        FLASK_ENV: testing

    - name: Lint with flake8
      run: |
        . venv/bin/activate && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
